application: your-app-id
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: helloworld_api.APPLICATION

libraries:
- name: pycrypto
  version: latest
